version: '3.8'

services:
  flask-challenge:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1008:5000"
    volumes:
      - .:/app
    container_name: flask-ctf-app
    restart: unless-stopped
